# apps/cert-manager/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://github.com/greensebastian/infra-oracle
      targetRevision: main
      ref: values
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: ">=0.0.0"
      helm:
        valueFiles:
          - $values/apps/cert-manager/values.yaml
    - repoURL: https://github.com/greensebastian/infra-oracle
      targetRevision: main
      path: apps/cert-manager/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
