# charts/httproute/templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Release.Name }}-tls"
  namespace: istio-system
spec:
  secretName: "{{ .Release.Name }}-tls"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.hostname }}