apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: "{{ .Release.Name }}-image-updater"
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: {{ .Release.Name }}
      images:
        - alias: {{ .Release.Name }}
          imageName: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          commonUpdateSettings:
            updateStrategy: "digest"