# apps/argocd/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/greensebastian/infra-oracle
      targetRevision: main
      ref: values
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: ">=0.0.0"
      helm:
        valueFiles:
          - $values/apps/argocd/values.yaml
    - repoURL: https://github.com/greensebastian/infra-oracle
      targetRevision: main
      path: charts/httproute
      helm:
        releaseName: argocd
        values: |
          hostname: argo.oci.sebastiangreen.se
          backendRef:
            name: argocd-server
            port: 80
            gatewayListenerName: argocd-https
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
