# apps/argocd/values.yaml
global:
  domain: argo.oci.sebastiangreen.se

configs:
  params:
    server.insecure: true
    timeout.reconciliation: 30s

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argo.oci.sebastiangreen.se
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls:
      - secretName: argocd-tls
        hosts:
          - argo.oci.sebastiangreen.se
