# apps/argocd/values.yaml
global:
  domain: argo.oci.sebastiangreen.se

configs:
  params:
    server.insecure: true
  cm:
    url: https://argo.oci.sebastiangreen.se
    timeout.reconciliation: 30s
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          hs.message = obj.status.health.message
        end
      end
      return hs

server:
  ingress:
    enabled: false
